name: maven-action
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: checkout-code
        uses: actions/checkout@v5
      - name: java install
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distributions: temurin
          java-package: jre
          cache: maven
          check-latest: false
          set-default: true
          verify-signature: false
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN
          overwrite-settings: true
          job-status: success
          token: ***
          show-download-progress: false
      - name: build
        run: mvn clean install
      
