name: maven-action
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: checkout-code
        uses: actions/checkout@v5
      - name: build
        run: mvn install
      
